name = "bdo-server"
main = "dist/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "bdo-server-prod"
routes = [
  { pattern = "api.tu-dominio.com/*", zone_name = "tu-dominio.com" }
]

[build]
command = "npm install && npx prisma generate && npm run build"

[env.production.vars]
NODE_ENV = "production"



